image: alpine

docs:
  script:
    - apk update && apk add doxygen
    - doxygen doxygen/Doxyfile
    - ls
    - ls doxygen
    - ls doxygen/documentation
    - ls documentation
  artifacts:
    paths:
      - documentation/html/